"""
Référentiel des technologies pour Consultator
Ce fichier contient la liste complète des technologies disponibles
"""

from typing import Dict
from typing import List

# Référentiel complet des technologies par catégorie
TECHNOLOGIES_REFERENTIEL: Dict[str, List[str]] = {
    "Langages de programmation": [
        "C",
        "C++",
        "C#",
        "Java",
        "Java 8",
        "Java 11",
        "Java 17",
        "Java 21",
        "Python",
        "Python 2.7",
        "Python 3.x",
        "Python 3.8+",
        "Python 3.9+",
        "Python 3.10+",
        "Python 3.11+",
        "Python 3.12+",
        "JavaScript",
        "TypeScript",
        "ECMAScript 6+",
        "Node.js",
        "PHP",
        "PHP 7.x",
        "PHP 8.x",
        "Ruby",
        "Ruby on Rails",
        "Go",
        "Golang",
        "Rust",
        "Kotlin",
        "Kotlin Multiplatform",
        "Swift",
        "Objective-C",
        "Scala",
        "R",
        "R Shiny",
        "MATLAB",
        "Perl",
        "Bash",
        "Shell scripting",
        "PowerShell",
        "SQL",
        "PL/SQL",
        "T-SQL",
        "HTML5",
        "CSS3",
        "SASS",
        "SCSS",
        "LESS",
        "Dart",
        "Flutter",
        "Elixir",
        "Erlang",
        "Haskell",
        "F#",
        "VB.NET",
        "COBOL",
        "Fortran",
        "Assembly",
    ],
    "Frameworks Web": [
        # Frontend
        "React",
        "React.js",
        "React Native",
        "Next.js",
        "Angular",
        "Angular 2+",
        "AngularJS",
        "Vue.js",
        "Vue 3",
        "Nuxt.js",
        "Svelte",
        "SvelteKit",
        "Ember.js",
        "Backbone.js",
        "jQuery",
        "Bootstrap",
        "Tailwind CSS",
        "Material-UI",
        "Ant Design",
        # Backend
        "Express.js",
        "Koa.js",
        "Fastify",
        "Django",
        "Flask",
        "FastAPI",
        "Tornado",
        "Spring",
        "Spring Boot",
        "Spring Cloud",
        "Spring Security",
        "Laravel",
        "Symfony",
        "CodeIgniter",
        "Ruby on Rails",
        "Sinatra",
        "ASP.NET",
        "ASP.NET Core",
        ".NET Framework",
        ".NET 5+",
        "Gin",
        "Echo",
        "Fiber",
        "Play Framework",
        "Phoenix",
    ],
    "Bases de données": [
        # Relationnelles
        "MySQL",
        "PostgreSQL",
        "SQLite",
        "MariaDB",
        "Oracle Database",
        "Oracle 11g",
        "Oracle 12c",
        "Oracle 19c",
        "Oracle 21c",
        "SQL Server",
        "SQL Server 2019",
        "SQL Server 2022",
        "IBM DB2",
        "SAP HANA",
        # NoSQL
        "MongoDB",
        "CouchDB",
        "CouchBase",
        "Redis",
        "Memcached",
        "Elasticsearch",
        "Solr",
        "Cassandra",
        "HBase",
        "DynamoDB",
        "Neo4j",
        "ArangoDB",
        "InfluxDB",
        "TimescaleDB",
        # Big Data
        "Apache Spark",
        "Apache Hadoop",
        "Apache Kafka",
        "Apache Storm",
        "Apache Flink",
        "Apache Beam",
        "Snowflake",
        "BigQuery",
        "Redshift",
    ],
    "Cloud & DevOps": [
        # Cloud Providers
        "AWS",
        "Amazon Web Services",
        "EC2",
        "S3",
        "Lambda",
        "RDS",
        "CloudFormation",
        "Microsoft Azure",
        "Azure",
        "Azure Functions",
        "Azure SQL",
        "Azure DevOps",
        "Google Cloud Platform",
        "GCP",
        "Google Cloud Functions",
        "Google Kubernetes Engine",
        "IBM Cloud",
        "Oracle Cloud",
        # Containerisation
        "Docker",
        "Docker Compose",
        "Docker Swarm",
        "Kubernetes",
        "K8s",
        "OpenShift",
        "Rancher",
        "Podman",
        "LXC",
        # CI/CD
        "Jenkins",
        "GitLab CI",
        "GitHub Actions",
        "Azure DevOps",
        "CircleCI",
        "Travis CI",
        "Bamboo",
        "TeamCity",
        # Infrastructure as Code
        "Terraform",
        "Ansible",
        "Puppet",
        "Chef",
        "SaltStack",
        "CloudFormation",
        "ARM Templates",
        "Pulumi",
        # Monitoring
        "Prometheus",
        "Grafana",
        "ELK Stack",
        "Elasticsearch",
        "Logstash",
        "Kibana",
        "Splunk",
        "Datadog",
        "New Relic",
        "AppDynamics",
    ],
    "Intelligence Artificielle & Data Science": [
        # Machine Learning
        "TensorFlow",
        "PyTorch",
        "Scikit-learn",
        "Keras",
        "XGBoost",
        "LightGBM",
        "CatBoost",
        "Apache Spark MLlib",
        "H2O.ai",
        "Pandas",
        "NumPy",
        "SciPy",
        "Matplotlib",
        "Seaborn",
        "Plotly",
        "Jupyter",
        "Google Colab",
        # Deep Learning
        "Neural Networks",
        "CNN",
        "RNN",
        "LSTM",
        "GAN",
        "Transformer",
        "BERT",
        "GPT",
        "OpenAI",
        "Hugging Face",
        # Computer Vision
        "OpenCV",
        "PIL",
        "Pillow",
        "ImageIO",
        # NLP
        "NLTK",
        "spaCy",
        "Gensim",
        "TextBlob",
        # Big Data & Analytics
        "Apache Spark",
        "Hadoop",
        "Hive",
        "Pig",
        "HBase",
        "Tableau",
        "Power BI",
        "QlikView",
        "Looker",
        "Apache Airflow",
        "Prefect",
    ],
    "Mobile": [
        "iOS",
        "Android",
        "React Native",
        "Flutter",
        "Xamarin",
        "PhoneGap",
        "Cordova",
        "Ionic",
        "Swift",
        "Objective-C",
        "Kotlin",
        "Java Android",
        "Unity",
        "Unreal Engine",
    ],
    "Outils de développement": [
        # IDE
        "Visual Studio Code",
        "IntelliJ IDEA",
        "Eclipse",
        "Visual Studio",
        "PyCharm",
        "WebStorm",
        "Android Studio",
        "Xcode",
        # Version Control
        "Git",
        "GitHub",
        "GitLab",
        "Bitbucket",
        "SVN",
        "Mercurial",
        # Build Tools
        "Maven",
        "Gradle",
        "Ant",
        "SBT",
        "npm",
        "yarn",
        "pnpm",
        "pip",
        "conda",
        "poetry",
        "Webpack",
        "Vite",
        "Rollup",
        "Parcel",
        # Testing
        "JUnit",
        "TestNG",
        "Mockito",
        "Jest",
        "Mocha",
        "Jasmine",
        "Cypress",
        "Selenium",
        "pytest",
        "unittest",
        "nose2",
        "Postman",
        "Insomnia",
    ],
    "Architecture & Design": [
        "Microservices",
        "SOA",
        "RESTful API",
        "GraphQL",
        "Event-driven architecture",
        "CQRS",
        "Event Sourcing",
        "Domain-Driven Design",
        "Clean Architecture",
        "Design Patterns",
        "SOLID Principles",
        "API Gateway",
        "Service Mesh",
        "Istio",
        "Message Queues",
        "RabbitMQ",
        "Apache Kafka",
        "Redis Pub/Sub",
    ],
    "Sécurité": [
        "OAuth",
        "JWT",
        "SAML",
        "LDAP",
        "Active Directory",
        "SSL/TLS",
        "HTTPS",
        "Cryptography",
        "Penetration Testing",
        "OWASP",
        "Security Scanning",
        "HashiCorp Vault",
        "AWS IAM",
        "Azure AD",
        "Firewalls",
        "VPN",
        "Network Security",
    ],
    "Systèmes d'exploitation": [
        "Linux",
        "Ubuntu",
        "CentOS",
        "RHEL",
        "Debian",
        "Alpine",
        "Windows",
        "Windows Server",
        "Windows 10",
        "Windows 11",
        "macOS",
        "Unix",
        "FreeBSD",
    ],
    "Méthodologies": [
        "Agile",
        "Scrum",
        "Kanban",
        "Lean",
        "DevOps",
        "GitOps",
        "DataOps",
        "MLOps",
        "TDD",
        "BDD",
        "DDD",
        "Continuous Integration",
        "Continuous Deployment",
        "ITIL",
        "Six Sigma",
    ],
}


def get_all_technologies() -> List[str]:
    """Retourne toutes les technologies du référentiel sous forme de liste plate"""
    all_techs = []
    for category, techs in TECHNOLOGIES_REFERENTIEL.items():
        all_techs.extend(techs)
    return sorted(list(set(all_techs)))


def get_technologies_by_category() -> Dict[str, List[str]]:
    """Retourne les technologies organisées par catégorie"""
    return TECHNOLOGIES_REFERENTIEL


def search_technologies(query: str) -> List[str]:
    """Recherche des technologies contenant le terme de recherche"""
    query_lower = query.lower()
    all_techs = get_all_technologies()
    return [tech for tech in all_techs if query_lower in tech.lower()]


def add_custom_technology(category: str, technology: str) -> bool:
    """Ajoute une technologie personnalisée à une catégorie"""
    if category not in TECHNOLOGIES_REFERENTIEL:
        TECHNOLOGIES_REFERENTIEL[category] = []

    if technology not in TECHNOLOGIES_REFERENTIEL[category]:
        TECHNOLOGIES_REFERENTIEL[category].append(technology)
        TECHNOLOGIES_REFERENTIEL[category].sort()
        return True
    return False


# Technologies populaires pour suggestions rapides
TECHNOLOGIES_POPULAIRES = [
    "Python",
    "Java",
    "JavaScript",
    "TypeScript",
    "C#",
    "Go",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Spring Boot",
    "Django",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "AWS",
    "Azure",
    "Docker",
    "Kubernetes",
    "Git",
    "Jenkins",
    "Terraform",
]
