name: 🧪 Tests et Couverture

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
    
    - name: Create test database
      run: |
        python -c "from app.database.database import init_database; init_database()"
    
    - name: Run tests with coverage
      run: |
        mkdir -p reports
        python -m pytest tests/ --cov=app --cov-report=xml --cov-report=html
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      if: matrix.python-version == '3.11'
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
    
    - name: Generate test report
      if: always()
      run: |
        mkdir -p reports
        python -m pytest tests/ --html=reports/pytest_report.html --self-contained-html
    
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports-${{ matrix.python-version }}
        path: |
          reports/
          htmlcov/

  regression-tests:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
    
    - name: Generate regression tests
      run: |
        python scripts/auto_test_generator.py
    
    - name: Run regression tests
      run: |
        python -m pytest tests/regression/ -v --tb=short
        
    - name: Coverage improvement analysis
      run: |
        python scripts/improve_coverage.py
        
    - name: Upload analysis reports
      uses: actions/upload-artifact@v4
      with:
        name: analysis-reports
        path: |
          TEST_IMPROVEMENT_PLAN.md
          tests/auto_generated/GENERATION_SUMMARY.md
