[global]

# Désactiver les avertissements de dépréciation pour development
showWarningOnDirectExecution = false

[logger]

# Réduire le niveau de log pour éviter les avertissements
level = "ERROR"

[client]

# Configuration pour éviter les analyses inutiles
showSidebarNavigation = true
showErrorDetails = false